// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commandMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "CommandMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CommandMessageRoot

@implementation CommandMessageRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum CommandEnum

GPBEnumDescriptor *CommandEnum_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "CmdDefault\000CmdTest\000CmdError\000CmdSystemLog"
        "out\000CmdHeartBeat\000";
    static const int32_t values[] = {
        CommandEnum_CmdDefault,
        CommandEnum_CmdTest,
        CommandEnum_CmdError,
        CommandEnum_CmdSystemLogout,
        CommandEnum_CmdHeartBeat,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(CommandEnum)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:CommandEnum_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL CommandEnum_IsValidValue(int32_t value__) {
  switch (value__) {
    case CommandEnum_CmdDefault:
    case CommandEnum_CmdTest:
    case CommandEnum_CmdError:
    case CommandEnum_CmdSystemLogout:
    case CommandEnum_CmdHeartBeat:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
