// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moduleMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BaseRspMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ModuleMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ModuleMessageRoot : GPBRootObject
@end

#pragma mark - Error_Rsp

typedef GPB_ENUM(Error_Rsp_FieldNumber) {
  Error_Rsp_FieldNumber_ErrorCode = 1,
};

@interface Error_Rsp : GPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@end

#pragma mark - Empty_Req

/**
 *  Empty request, equal to Get
 **/
@interface Empty_Req : GPBMessage

@end

#pragma mark - Empty_Rsp

typedef GPB_ENUM(Empty_Rsp_FieldNumber) {
  Empty_Rsp_FieldNumber_BaseRsp = 101,
};

@interface Empty_Rsp : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BaseRspMessage *baseRsp;
/** Test to see if @c baseRsp has been set. */
@property(nonatomic, readwrite) BOOL hasBaseRsp;

@end

#pragma mark - BaseRspMessage

typedef GPB_ENUM(BaseRspMessage_FieldNumber) {
  BaseRspMessage_FieldNumber_Level = 1,
  BaseRspMessage_FieldNumber_ResMap = 50,
};

/**
 * Handle resource change
 **/
@interface BaseRspMessage : GPBMessage

@property(nonatomic, readwrite) int32_t level;

/** <ResProtoType, value> */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Int32Dictionary *resMap;
/** The number of items in @c resMap without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resMap_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
